### ISSUE TITLE
"Formatter ... unknown" error on startup

### ISSUE THREAD

**Issue by entrity** [skroutz/rspecq#71]
I have not gotten rspecq to run successfully. When I execute `bundle exec rspecq  -b mybuild -w myworker`, I get the following error message and stack.

```
bundler: failed to load command: rspecq (/home/me/workspace/vendor/bundle/bin/rspecq)
ArgumentError: Formatter '#<RSpecQ::Formatters::FailureRecorder:0x00007f07da84beb0>' unknown - maybe you meant 'documentation' or 'progress'?.
  /home/me/workspace/vendor/bundle/gems/rspec-core-3.6.0/lib/rspec/core/formatters.rb:178:in `find_formatter'
  /home/me/workspace/vendor/bundle/gems/rspec-core-3.6.0/lib/rspec/core/formatters.rb:146:in `add'
  /home/me/workspace/vendor/bundle/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:876:in `add_formatter'
  /home/me/workspace/vendor/bundle/gems/rspecq-0.7.2/lib/rspecq/worker.rb:122:in `block in work'
  /home/me/workspace/vendor/bundle/gems/rspecq-0.7.2/lib/rspecq/worker.rb:94:in `loop'
  /home/me/workspace/vendor/bundle/gems/rspecq-0.7.2/lib/rspecq/worker.rb:94:in `work'
  /home/me/workspace/vendor/bundle/gems/rspecq-0.7.2/bin/rspecq:182:in `<top (required)>'
  /home/me/workspace/vendor/bundle/bin/rspecq:23:in `load'
  /home/me/workspace/vendor/bundle/bin/rspecq:23:in `<top (required)>'
```
I'm on rspecq 0.7.2 and rspec-core 3.4.4.

It looks like `rspecq/worker.rb` is trying to pass formatter instances to `RSpec.configuration.add_formatter`, but downstream from that function, it appears that `RSpec::Core::Formatters::Loader#custom_formatter` expects either a string or a class. Am I reading this correctly?

**Comment by entrity** [comment]
This may just be a matter of needing to specify a minimum version for rspec-core in the RspecQ gemspec file. I started out on rspec 3.4.4, and `non_example_failure` (used by RspecQ) doesn't show up until 3.6.

After bumping my rspec to 3.9, my execution of `rspecq` appears to succed.
